import type { Metadata } from "next";
import { Righteous, Poiret_One, Belanosima, Cormorant_Upright, MuseoModerno } from "next/font/google";
import "./globals.css";

const righteous = Righteous({
  weight: "400",
  variable: "--font-righteous",
  subsets: ["latin"],
});

const museoModerno = MuseoModerno({
    weight: "400",
    variable: "--font-museo-moderno",
    subsets: ["latin"],
    });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${museoModerno.variable} ${righteous.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
